name: Code Style Check

on: [push, pull_request]

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List files in the directory (debugging)
        run: ls -la

      - name: Run flake8 (debugging without output file)
        run: |
          flake8 --version  # Verify flake8 is installed and working
          flake8 .  # Run flake8 without output file

      - name: Run flake8 with JSON output
        run: |
          flake8 --output-file=report.json --format=json .

      - name: Upload flake8 report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flake8-report
          path: report.json


